riding_sport_clubs/riding_sport_clubs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('riding_sport_clubs.web_clubs.urls')),
    path('account/', include('riding_sport_clubs.web_accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

riding_sport_clubs/riding_sport_clubs/web_clubs/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models
from riding_sport_clubs.base_validators.validators import owner_name_validator, name_validator, phone_number_validator


class Club(models.Model):
    CLUB_NAME_MIN_LENGTH = 2
    CLUB_NAME_MAX_LENGTH = 50
    OWNER_NAME_MIN_LENGTH = 2
    OWNER_NAME_MAX_LENGTH = 35
    UPLOAD_CLUB_LOGO = 'clubs_logo'

    club_name = models.CharField(
        max_length=CLUB_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(CLUB_NAME_MIN_LENGTH),
        ),
        unique=True,
    )

    owner = models.CharField(
        max_length=OWNER_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(OWNER_NAME_MIN_LENGTH),
            owner_name_validator,
        ),
    )

    email_club = models.EmailField()

    award_gold = models.IntegerField(
        default=0,
    )

    award_silver = models.IntegerField(
        default=0,
    )

    award_bronze = models.IntegerField(
        default=0,
    )

    rating = models.IntegerField(
        default=0,
    )

    address = models.TextField(
        null=True,
        blank=True,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    club_logo = models.ImageField(
        upload_to=UPLOAD_CLUB_LOGO,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.club_name


class Trainer(models.Model):
    TRAINER_FIRST_NAME_MAX_LENGTH = 25
    TRAINER_LAST_NAME_MAX_LENGTH = 25
    AGE_MIN_VALUE = 1
    TRAINER_NUMBER_MAX_LENGTH = 16
    TRAINER_NUMBER_MIN_LENGTH = 8
    UPLOAD_TRAINER_PHOTO = 'trainer_photos'

    trainer_first_name = models.CharField(
        max_length=TRAINER_FIRST_NAME_MAX_LENGTH,
        validators=(
            name_validator,
        ),
    )

    trainer_last_name = models.CharField(
        max_length=TRAINER_LAST_NAME_MAX_LENGTH,
        validators=(
            name_validator,
        ),
    )

    trainer_age = models.IntegerField(
        validators=(
            MinValueValidator(AGE_MIN_VALUE),
        ),
    )

    trainer_phone_number = models.CharField(
        max_length=TRAINER_NUMBER_MAX_LENGTH,
        validators=(
            MinLengthValidator(TRAINER_NUMBER_MIN_LENGTH),
            phone_number_validator,
        ),
        null=True,
        blank=True,
    )

    trainer_photo = models.ImageField(
        upload_to=UPLOAD_TRAINER_PHOTO,
        null=True,
        blank=True,
    )

    trainer_info = models.TextField(
        null=True,
        blank=True,
    )

    clubs = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.trainer_first_name}  {self.trainer_last_name}"


class HorseBreed(models.Model):
    BREED_MAX_LENGTH = 35
    COLOR_MAX_LENGTH = 40
    USES_MAX_LENGTH = 40
    DESCRIPTION_MAX_LENGTH = 400000

    breed = models.CharField(
        max_length=BREED_MAX_LENGTH,
        choices={
            ('Arabian', 'Arabian'),
            ('Andalusian', 'Andalusian'),
            ('Friesian', 'Friesian'),
        }
    )

    average_height = models.IntegerField()

    horse_color = models.CharField(
        max_length=COLOR_MAX_LENGTH,
    )

    common_uses = models.CharField(
        max_length=USES_MAX_LENGTH,
    )

    breed_description = models.TextField(
        max_length=DESCRIPTION_MAX_LENGTH,
    )

    def __str__(self):
        return self.breed

riding_sport_clubs/templates/web/authorization.html
{% extends 'bases/base.html' %}
{% load static %}

{% block base %}
    <div class="video">
        <video class="horse" autoplay muted playsinline loop>
            <source src="{% static 'video/base_horse_video.mp4' %}"></video>
    </div>
    <div class="text">
        <h1 style="color: darkred;">Access denied contact us!</h1>
    </div>
{% endblock %}

riding_sport_clubs/templates/web/club_info.html
{% extends 'bases/base.html' %}
{% load static %}


{% block base %}
     <div class="row">
        <div class="clubCover">
            <img style="object-fit: inherit;width: 300px;height: 180px;" src="{{ club.club_logo.url }}" alt="Club Image">
            <div class="button">
                <a>EditClub</a>
            </div>
        </div>
        <div class="clubInfo">
            <div class="clubText">
                <p style="font-family: Papyrus fantasy; font-size: 30px; color: #274060;padding-top: 15px; text-align: center"><i>{{ club.club_name }}</i></p>
                <p style="font-family: Papyrus fantasy; font-size: 30px; color: #274060;padding-top: 15px;"><i>{{ club.description }}</i></p>
                <p style="text-align: center; font-size: 30px; color: green">Trainers</p>
                {% for trainer in club.trainer_set.all %}
                    <p style="font-family: Papyrus fantasy; font-size: 30px; color: #274060;padding-top: 15px;"><i>{{ trainer}}</i></p>
                {% endfor %}
                <p style="font-family: Papyrus fantasy; font-size: 30px; color: #274060;padding-top: 15px;">Email: <i>{{ club.email_club}}</i></p>
                <p style="font-family: Papyrus fantasy; font-size: 30px; color: #274060;padding-top: 15px;">Address: <i>{{ club.address}}</i></p>
            </div>
        </div>
     </div>
{% endblock %}

riding_sport_clubs/templates/web/clubs_list.html
{% extends 'bases/base.html' %}
{% load static %}

{% block base %}
    {% if object_list %}
    <section id="catalogPage">
        {% for club in object_list %}
            <div class="card-box">
                <img style="border: 1px solid #1b2845" src="{{ club.club_logo.url }}" alt="Club Image">
            <div class="text-center">
                <p class="name" style="color: #45a29e">Club Name: {{ club.club_name }}</p>
                <p class="owner" style="color: #45a29e">Owner: {{ club.owner }}</p>
                {% for trainer in club.trainer_set.all %}
                    <p class="genre" style="color: #45a29e">Trainer: {{ trainer }}</p>
                {% endfor %}
                <p class="awards">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffd700" class="bi bi-award-fill" viewBox="0 0 16 16">
                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                    </svg>
                    <i>{{ club.award_gold }}</i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#bfc1c2" class="bi bi-award-fill" viewBox="0 0 16 16">
                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                    </svg>
                    <i>{{ club.award_silver }}</i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#cdab7e" class="bi bi-award-fill" viewBox="0 0 16 16">
                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                    </svg>
                    <i>{{ club.award_bronze }}</i>
                </p>
                <p class="rating" style="color: #EF7D00;font-style: oblique ">Rating: {{ club.rating }}
                    {% if request.user.is_authenticated %}
                        <a class="likes" href="{% url 'like club' club.pk %}" style="margin-left: 10px;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#EF7D00" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                            <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                            </svg>
                        </a>
                    {% endif %}
                </p>
            </div>
            <div class="btn-group">
                <a href="{% url 'club info' club.pk %}">More Info</a>
            </div>
            </div>
        {% endfor %}
    </section>
    {% else %}
        <h2>No clubs yet!</h2>
    {% endif %}
{% endblock %}

riding_sport_clubs/templates/web/create_club.html
{% extends 'bases/base_registrations_page.html' %}

{% block base_registar %}
    <div class="body">
        <h1 style="text-decoration: overline underline darkgoldenrod">Registration</h1>
        <div class="form">
            <form method="post" action="{% url 'create club' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="SUBMIT" />
            </form>
        </div>
    </div>
{% endblock %}

riding_sport_clubs/templates/web/home.html
{% extends 'bases/base.html' %}
{% load static %}

{% block base %}
    <div class="video">
        <video class="horse" autoplay muted playsinline loop>
            <source src="{% static 'video/base_horse_video.mp4' %}"></video>
    </div>
    <div class="text">
        <h1>Discover the greatest riding sport clubs</h1>
    </div>
{% endblock %}

riding_sport_clubs/templates/web/home_breeds.html
{% extends 'bases/base_registrations_page.html' %}
{% load static %}

{% block base_registar %}
    <div class="gallery">
      <a target="_blank" href="{% url 'racing info' %}">
        <img src="{% static 'images/breeds_pictures/arabian.jpg' %}" alt="Arabian" width="600" height="400">
      </a>
      <div class="desc">Arabian Horse Breed</div>
    </div>
    <div class="gallery">
      <a target="_blank" href="{% url 'racing info' %}">
        <img src="{% static 'images/breeds_pictures/friesians.jpg' %}" alt="Friesian" width="600" height="400">
      </a>
      <div class="desc">Friesian Horse Breed</div>
    </div>
    <div class="gallery">
      <a target="_blank" href="{% url 'racing info' %}">
        <img src="{% static 'images/breeds_pictures/andalusian.jpg' %}" alt="Andalusian" width="600" height="400">
      </a>
      <div class="desc">Andalusian Horse Breed</div>
    </div>
{% endblock %}

riding_sport_clubs/templates/web/pay_page.html
{% extends 'bases/base_registrations_page.html' %}

{% block base_registar %}
    <div class="body">
        <h1 style="text-decoration: overline underline darkgoldenrod">Payment</h1>
        <div class="form">
            <form method="get" action="{% url 'create club' %}" enctype="multipart/form-data">
                {% csrf_token %}

                <input type="submit" value="Go To Register" />
            </form>
        </div>
    </div>
{% endblock %}

riding_sport_clubs/templates/web/racing_info.html
{% extends 'bases/base.html' %}
{% load static %}


{% block base %}
    <div class="text">
        <h1 style="color: goldenrod;">Our page is almost ready.<br>Please come back soon!</h1>
    </div>
{% endblock %}